# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    #    allowed_methods_listener:  true
    body_converter:
        enabled: true
    view:
        view_response_listener: 'force'
        empty_content: 204
        failed_validation: 422
        formats:
            json: true
    exception:
        enabled: true
    format_listener:
        rules:
            - { path: '^/api/v1', prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/', prefer_extension: true, fallback_format: json, priorities: [ json ]  }

    serializer:
        groups: ["rest"]

    service:
        view_handler: app.view.view_handler
